import "@/styles/global.scss";

import type { Metadata } from "next";
import { Inter as Cardo } from "next/font/google";

import { ThemeProvider } from "@/components/provider/theme-provider";
import MainLayout from "@/layouts/main-layout";
import { StoreProvider } from "@/stores/store-provider";

const fontSans = Cardo({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Silky - Ecommerce platform ",
  description: "Generated by Silky - Ecommerce platform ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontSans.className}>
        <StoreProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <MainLayout>{children}</MainLayout>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
