import "@/styles/global.scss";
import "react-toastify/dist/ReactToastify.css";

import type { Metadata } from "next";
import { Inter as Cardo } from "next/font/google";
import { ToastContainer } from "react-toastify";

import { ThemeProvider } from "@/components/provider/theme-provider";
import MainLayout from "@/layouts/main-layout";
import { StoreProvider } from "@/stores/store-provider";
import { Suspense } from "react";
import LoadingGlobal from "@/components/loading/global";

const fontSans = Cardo({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Silky - Ecommerce platform ",
  description: "Generated by Silky - Ecommerce platform ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontSans.className}>
        <StoreProvider>
          <Suspense fallback={<LoadingGlobal />}>
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              <MainLayout>{children}</MainLayout>
              <ToastContainer />
            </ThemeProvider>
          </Suspense>
        </StoreProvider>
      </body>
    </html>
  );
}
